// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Waracle.HotelBooking.Data.Models;

public partial class Booking
{
    public Guid Id { get; set; }

    public int RoomId { get; set; }

    public DateOnly DateStart { get; set; }

    public DateOnly DateEnd { get; set; }

    public string GuestName { get; set; }

    public string GuestTelNo { get; set; }

    public virtual Room Room { get; set; }
}