// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Waracle.HotelBooking.Data.Models;

public partial class Room
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int HotelId { get; set; }

    public int TypeId { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual Hotel Hotel { get; set; }

    public virtual RoomType Type { get; set; }
}